### ISSUE TITLE
Hashing.(Feautre Suggestion)

### ISSUE THREAD

**Issue by Richard5656** [AudioTore/termi#1]
Hi its Pablo here,
I would like to suggest a feauture. What if instead of storing the password and the username in plaintext we hash them and then stored them. Hashing is sort of like encryption. Servers store passwords in hashes because its more secure than storing them in plaintext.

**Comment by Richard5656** [comment]
We can try using hashlib for this or we can use the python built in hash function. 

https://www.geeksforgeeks.org/md5-hash-python/

https://www.geeksforgeeks.org/python-hash-method/#:~:text=Python%20hash%20%28%29%20function%20is%20a%20built-in%20function,Python%20hash%20%28%29%20method%3A%20Syntax%20%3A%20hash%20%28obj%29

**Comment by Richard5656** [comment]
Oh and the hashes can be compared instead of the passwords.

**Comment by AudioTore** [comment]
I will try that

**Comment by AudioTore** [comment]
hmm.. I can't seem to do that. however i could change the txt file to something that you can't open
