### ISSUE TITLE
About the links and c-matrix

### ISSUE THREAD

**Issue by Richard5656** [AudioTore/termi#4]
Wouldnt it be easier to create some sort installer to install links and c-matrix during the setup?

-Pablo

**Comment by AudioTore** [comment]
@Richard5656 i will see what i can do with that

**Comment by AudioTore** [comment]
@Richard5656 what distro do you use?

**Comment by Richard5656** [comment]
I mainly use the debian distro but it should be possible to check for all the mainly used distros in python and install accordingly to the distro. Like sudo apt install and sudo pacman.

**Comment by Richard5656** [comment]
Why did you delete your channel?

**Comment by AudioTore** [comment]
Im giving it up

**Comment by AudioTore** [comment]
Don't worry its back

**Comment by Richard5656** [comment]
Oh cool. About the installer we could use python to detect the system and use the according package manager. 

On a Side Note: I'm starting a programing team wanna join?

**Comment by AudioTore** [comment]
Sure!

**Comment by AudioTore** [comment]
@Richard5656 New TermI update!

**Comment by Richard5656** [comment]
Oh thank you for joining. Wow!!! the terminal really looks like its coming together well. Even used tkinter.

**Comment by AudioTore** [comment]
@Richard5656 Do you have a discord?

**Comment by Richard5656** [comment]
Sorry I dont have one.

**Comment by AudioTore** [comment]
@Richard5656 Alright

**Comment by Richard5656** [comment]
Ill sign up for one when I have time.

**Comment by AudioTore** [comment]
@Richard5656 Cool! But just so you know i might just stop uploading content. Because i started the channel kind of as a hobby and to be fair i don't really Enjoy it.

**Comment by Richard5656** [comment]
Hey its ok. Sorry if I made you feel like you were being pressured to make videos.

**Comment by AudioTore** [comment]
@Richard5656 What? No it wasn't you at all! It's just it got boring after a bit.

**Comment by Richard5656** [comment]
Oh ok

**Comment by Richard5656** [comment]
Ok we should put everything in functions and make it all in a single module. We could put all the functions into diffrent classes into the same module to sort them if you want.

**Comment by AudioTore** [comment]
@Richard5656 i will think about it.
